import { test, expect, type APIRequestContext, type Page } from '@playwright/test';
import { createHash, randomUUID } from 'node:crypto';
import { createNeutralNativeBotPackage } from '../core/native-bot.js';
import { defaultHiddenStoryConfig } from '../core/hidden-story.js';
import { createHiddenNativeFixture } from './fixtures/hidden-native.js';
import type { Chat, ChatDetail, Run } from '../core/types.js';
import type { PromptProgram } from '../core/prompt-program.js';

async function detail(request: APIRequestContext, id: string): Promise<ChatDetail> { const response = await request.get(`/api/chats/${id}`); expect(response.ok()).toBe(true); return response.json(); }
async function chat(request: APIRequestContext, title: string): Promise<Chat> { const response = await request.post('/api/chats', { data: { title } }); expect(response.ok()).toBe(true); return response.json(); }
async function generate(request: APIRequestContext, id: string) { const before = await detail(request,id); const response = await request.post(`/api/chats/${id}/runs`, {data:{request:'Synthetic harbor scene.',expectedRevision:before.chat.headRevision,expectedSettingsRevision:before.chat.settingsRevision,expectedProfileRevision:before.profile!.revision,idempotencyKey:randomUUID()}}); expect(response.ok()).toBe(true); const run = await response.json() as Run; await expect.poll(async()=>(await detail(request,id)).runs.find(r=>r.id===run.id)?.status).toBe('completed'); }
async function settings(page:Page,id:string) { await page.goto(`/?chat=${id}`); await page.getByRole('button',{name:'채팅 설정',exact:true}).click(); return page.getByRole('dialog',{name:'채팅 설정',exact:true}); }
async function fits(page:Page) { expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); const dialog=page.getByRole('dialog').filter({visible:true}); if(await dialog.count()) expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true); }
const program:PromptProgram={version:1,controls:[{id:'tone',label:'합성 분위기',type:'select',default:null,options:[{label:'차분하게',value:'calm'},{label:'활기차게',value:'bright'}]}],blocks:[
  {id:'system',title:'합성 지침',kind:'message',role:'system',template:[{kind:'text',text:'SYNTHETIC TONE='},{kind:'value',expression:{control:'tone'}}]},
  {id:'user',title:'합성 예시 질문',kind:'message',role:'user',template:[{kind:'text',text:'Synthetic example question.'}]},
  {id:'assistant',title:'합성 예시 응답',kind:'message',role:'assistant',template:[{kind:'text',text:'Synthetic example response.'}],completion:'complete'},
  {id:'history',title:'합성 대화 범위',kind:'history',from:0,to:'end'},
]};

test('NUI01 native prompt import, draft preservation, roles, history and saved combinations',async({page,request},info)=>{
  test.setTimeout(60000); const c=await chat(request,'Synthetic native prompt UI'); await generate(request,c.id); const before=await detail(request,c.id); const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1440,height:1000}); const dialog=await settings(page,c.id); await dialog.getByRole('tab',{name:'프롬프트·창작 프리셋',exact:true}).click(); const editor=page.getByTestId('prompt-editor');
  await editor.getByLabel('불러올 프롬프트',{exact:true}).selectOption('new'); await editor.getByLabel('프롬프트 이름',{exact:true}).fill('Synthetic native composed'); await editor.getByRole('button',{name:'구성 편집',exact:true}).click(); const composer=page.getByTestId('prompt-composer');
  await composer.getByLabel('프롬프트 구성 JSON 불러오기',{exact:true}).setInputFiles({name:'synthetic-native-pheme.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({program,suggestedCombination:{id:'suggested',title:'합성 권장',values:{tone:'bright'}}}))});
  await expect(composer.locator('.pc-block')).toHaveCount(4); await expect(composer.getByLabel('합성 분위기',{exact:true})).toHaveValue('null'); await composer.getByRole('button',{name:'가져온 권장 조합을 목록에 추가',exact:true}).click(); await expect(composer.getByLabel('합성 분위기',{exact:true})).toHaveValue('null');
  const jsonSection=composer.locator('.pc-section').filter({has:page.locator('summary',{hasText:'전체 구성 JSON · 고급 편집'})}); await jsonSection.locator('summary').first().click(); const raw=composer.getByLabel('전체 프롬프트 구성 JSON',{exact:true}); await raw.fill('{ malformed native JSON'); await jsonSection.getByRole('button',{name:'JSON 적용',exact:true}).click(); await expect(raw).toHaveValue('{ malformed native JSON'); await expect(composer.locator('.pc-block')).toHaveCount(4); await jsonSection.getByRole('button',{name:'적용된 값으로 되돌리기',exact:true}).click(); await expect(raw).toHaveValue(JSON.stringify(program,null,2)); await jsonSection.locator('summary').first().click();
  await editor.getByRole('button',{name:'저장하고 이야기에 적용',exact:true}).click(); await expect.poll(async()=>(await detail(request,c.id)).profile?.prompts?.main?.id).toBeTruthy();
  await composer.getByLabel('합성 분위기',{exact:true}).selectOption('"calm"'); await composer.getByLabel('새 조합 이름',{exact:true}).fill('차분한 장면'); await composer.getByRole('button',{name:'현재 값으로 조합 만들기',exact:true}).click();
  await composer.getByLabel('합성 분위기',{exact:true}).selectOption('"bright"'); await composer.getByLabel('프롬프트 선택 조합',{exact:true}).selectOption({label:'차분한 장면'}); await expect(composer.getByLabel('합성 분위기',{exact:true})).toHaveValue('"calm"'); await composer.getByRole('button',{name:'이야기 선택값과 조합 저장',exact:true}).click();
  const after=await detail(request,c.id); const selected=after.profile!.prompts!.main!; const state=after.profile!.promptControls![`${selected.id}@${selected.revision}`]; expect(state.values).toEqual({tone:'calm'}); expect(state.combinations).toHaveLength(2); expect(state.combinations.map(item=>item.title)).toEqual(expect.arrayContaining(['합성 권장','차분한 장면'])); expect(after.profile!.routes.main).toEqual(before.profile!.routes.main);
  await composer.getByLabel('미리보기 현재 요청',{exact:true}).fill('Synthetic next turn.'); await composer.getByRole('button',{name:'미리보기 갱신',exact:true}).click(); await expect(composer.locator('.pc-message-list > li')).toHaveCount(7); const roles=await composer.locator('.pc-message-list > li > details > summary').allTextContents(); expect(roles.map(x=>x.match(/\. (system|user|assistant) /)?.[1])).toEqual(['system','user','assistant','user','user','assistant','user']);
  await composer.locator('.pc-message-list > li').first().locator('summary').click(); await expect(composer.locator('.pc-message-list pre').first()).toHaveText('SYNTHETIC TONE=calm'); await fits(page); await page.screenshot({path:info.outputPath('native-composer-desktop.png')});
  await composer.getByRole('button',{name:'구성 편집',exact:true}).click(); const firstBlock=composer.locator('.pc-block').first(); await firstBlock.locator('summary').first().click(); await expect(firstBlock.getByRole('combobox',{name:'메시지 역할',exact:true})).toHaveValue('system');
  for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]] as const){await page.setViewportSize({width,height});await firstBlock.evaluate(el=>el.scrollIntoView({block:'start'}));await fits(page);await page.screenshot({path:info.outputPath(`native-composer-block-${name}.png`)});}
  await firstBlock.locator('summary').first().click();const historyBlock=composer.locator('.pc-block').last();await historyBlock.locator('summary').first().click();await expect(historyBlock.getByLabel('시작 위치',{exact:true})).toHaveValue('0');await historyBlock.evaluate(el=>el.scrollIntoView({block:'start'}));await fits(page);await page.screenshot({path:info.outputPath('native-composer-history-mobile.png')});await historyBlock.locator('summary').first().click();
  await page.setViewportSize({width:390,height:844}); await composer.scrollIntoViewIfNeeded(); await fits(page); await page.screenshot({path:info.outputPath('native-composer-mobile.png')}); await page.reload(); await page.getByRole('button',{name:'채팅 설정',exact:true}).click(); await page.getByRole('tab',{name:'프롬프트·창작 프리셋',exact:true}).click(); await expect(page.getByTestId('prompt-composer').getByLabel('합성 분위기',{exact:true})).toHaveValue('"calm"');
  const final=await detail(request,c.id); expect(final.runs).toEqual(before.runs); expect(final.attempts).toEqual(before.attempts); expect(errors).toEqual([]);
});

test('NUI02 native bot localized controls clamp state and stage a scene without generation',async({page,request},info)=>{
  const c=await chat(request,'Synthetic native bot UI'), before=await detail(request,c.id); const pkg=createNeutralNativeBotPackage(); pkg.id=`synthetic-ui-${randomUUID()}`; pkg.title='합성 일상 UI 봇'; pkg.provenance.mode='synthetic'; const dialog=await settings(page,c.id); const panel=dialog.getByRole('region',{name:'네이티브 봇',exact:true});
  await panel.getByLabel('패키지 JSON 가져오기',{exact:true}).setInputFiles({name:'synthetic-bot.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))}); await expect(panel.getByRole('combobox',{name:'사용할 패키지',exact:true}).locator('option:checked')).toHaveText(pkg.title + ' · v1'); await panel.getByRole('button',{name:'이 분기에 적용 · 설정 초기화',exact:true}).click(); await expect(panel.getByLabel('친밀도',{exact:true})).toHaveValue('30');
  await panel.getByLabel('친밀도',{exact:true}).fill('150'); await panel.getByRole('button',{name:'친밀도 적용',exact:true}).click(); await expect(panel.getByLabel('친밀도',{exact:true})).toHaveValue('100'); await panel.getByRole('combobox',{name:'언어',exact:true}).selectOption('kr'); await expect(panel.getByRole('combobox',{name:'언어',exact:true})).toHaveValue('kr');
  for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]] as const){await page.setViewportSize({width,height});await panel.getByRole('heading',{name:'네이티브 봇',exact:true}).evaluate(el=>el.scrollIntoView({block:'start'}));await fits(page);await page.screenshot({path:info.outputPath(`native-bot-controls-${name}.png`)});}
  await panel.locator('button[aria-pressed]').filter({hasText:pkg.scenes[0].title.kr}).click(); await expect(panel.locator('aside')).toContainText(pkg.scenes[0].request.kr); await expect(panel.getByRole('img',{name:'합성 일상 심볼',exact:true})).toBeVisible(); await fits(page); await page.screenshot({path:info.outputPath('native-bot-mobile.png')}); await panel.getByRole('button',{name:'작성란에 넣기',exact:true}).click(); await expect(page.getByLabel('다음 장면 요청',{exact:true})).toHaveValue(pkg.scenes[0].request.kr);
  const after=await detail(request,c.id); expect(after.runs).toEqual(before.runs); expect(after.attempts).toEqual(before.attempts); expect(after.sources).toEqual(before.sources); expect(after.profile!.routes.main).toEqual(before.profile!.routes.main); const stateResponse=await request.get(`/api/chats/${c.id}/native-bot?branchId=main:${c.id}`); expect(stateResponse.ok()).toBe(true); const snapshot=await stateResponse.json(); expect(snapshot.state).toMatchObject({affection:100,language:'kr',sceneId:pkg.scenes[0].id}); expect(snapshot.pending.request).toBe(pkg.scenes[0].request.kr);
});

test('NUI03 hidden reader expands without writes and displays the current translated source',async({page,request},info)=>{
  const c=await chat(request,'Synthetic hidden reader UI');
  const conversion=createHiddenNativeFixture();
  const imported=await request.post('/api/hidden-story/modules',{data:{title:'Synthetic hidden reader',conversion}}); expect(imported.ok()).toBe(true); const module=await imported.json(); const profile=(await detail(request,c.id)).profile!; const config=defaultHiddenStoryConfig('nonsexual'); config.values['hidden.open']=0;
  const selected=await request.put(`/api/chats/${c.id}/hidden-story`,{data:{expectedRevision:profile.revision,selection:{module:{id:module.id,revision:module.revision},config}}}); expect(selected.ok()).toBe(true); await generate(request,c.id); const source=(await detail(request,c.id)).sources[0];
  const text='Main harbor arrival.\n\n@hsTitle: Quiet Tower\n⟦Tower @ Dawn @ Mira⟧\nMira recalls a blue bell.\n@hs\n\nMain crossing.\n\n@hsTitle: Old Letter\nAnother traveler remembers winter.\n@hs\n\nMain departure.'; const edited=await request.put(`/api/sources/${source.id}/text`,{data:{text,expectedRevision:source.editRevision??0}}); expect(edited.ok()).toBe(true); const before=await detail(request,c.id);
  await page.goto(`/?chat=${c.id}`); const reader=page.locator('.native-hidden-reader'); await expect(reader).toBeVisible(); const sections=reader.locator(':scope > .native-main-segment, :scope > details.native-hidden-story'); expect(await sections.evaluateAll(elements=>elements.map(el=>el.tagName==='DETAILS'?'hidden':'main'))).toEqual(['main','hidden','main','hidden','main']); const hidden=reader.locator('details.native-hidden-story'); await expect(hidden).toHaveCount(2); expect(await hidden.first().getAttribute('open')).toBeNull(); await hidden.first().locator('summary').click(); await expect(hidden.first()).toHaveAttribute('open',''); await expect(hidden.first()).toContainText('Mira recalls a blue bell.'); await expect(hidden.first().getByRole('list',{name:'이 장면의 장소와 시점'})).toHaveCount(0); await expect(hidden.first().locator('dl')).toContainText('Tower'); await expect(reader).toContainText('등장인물에게 정보가 전달되지는');
  await fits(page); await page.screenshot({path:info.outputPath('hidden-reader-mobile.png')}); await page.setViewportSize({width:1440,height:1000}); await fits(page); await page.screenshot({path:info.outputPath('hidden-reader-desktop.png')}); await hidden.first().locator('summary').click();
  const after=await detail(request,c.id); expect(after.sources).toEqual(before.sources); expect(after.runs).toEqual(before.runs); expect(after.attempts).toEqual(before.attempts); expect(after.profile).toEqual(before.profile); expect(after.sources[0].hash).toBe(createHash('sha256').update(text).digest('hex'));
  await page.getByRole('button',{name:'번역 보기',exact:true}).click();await expect.poll(async()=>(await detail(request,c.id)).jobs.find(job=>job.kind==='translation'&&job.sourceRevision===source.id)?.status).toBe('completed');
  const translatedBaseline=await detail(request,c.id);const translatedJob=translatedBaseline.jobs.find(job=>job.kind==='translation'&&job.sourceRevision===source.id)!;
  expect(translatedJob.sourceHash).toBe(before.sources[0].hash);expect(translatedJob.result).toMatchObject({sourceRevision:source.id,sourceHash:before.sources[0].hash,mock:true,text});
  expect(translatedJob.result!.segments!.flatMap(segment=>segment.anchors)).toEqual(before.sources[0].blocks!.map(block=>block.anchor));
  await expect(page.getByRole('button',{name:'번역 보기',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'원문 보기',exact:true})).toHaveAttribute('aria-pressed','false');
  // Hidden mock translation echoes source text so marker placement survives. Check
  // the validated translation slot, not a prefix that would corrupt its delimiters.
  await expect(page.getByTestId('source-text')).toHaveCount(0);const translatedBody=page.getByTestId('translation-text');await expect(translatedBody).toBeVisible();
  const translatedReader=translatedBody.locator('.native-hidden-reader');await expect(translatedReader.locator('details.native-hidden-story')).toHaveCount(2);await translatedReader.locator('details.native-hidden-story').first().locator('summary').click();await expect(translatedReader).toContainText('Mira recalls a blue bell.');
  for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]] as const){await page.setViewportSize({width,height});await translatedReader.evaluate(el=>el.scrollIntoView({block:'start'}));await fits(page);await page.screenshot({path:info.outputPath(`hidden-translation-${name}.png`)});}
  const translated=await detail(request,c.id);expect(translatedJob.revision).toBe((before.sources[0].translationRevision??0)+1);
  expect(translated.sources).toEqual(before.sources.map(item=>item.id===source.id?{...item,translationRevision:translatedJob.revision}:item));expect(translated.runs).toEqual(before.runs);expect(translated.profile).toEqual(before.profile);expect(translated.jobs.filter(job=>job.kind==='translation')).toHaveLength(1);
  const priorAttemptIds=new Set(before.attempts!.map(attempt=>attempt.id));expect(translatedBaseline.attempts!.filter(attempt=>priorAttemptIds.has(attempt.id))).toEqual(before.attempts);
  const translationAttempts=translatedBaseline.attempts!.filter(attempt=>!priorAttemptIds.has(attempt.id));expect(translationAttempts).toHaveLength(1);expect(translationAttempts[0]).toMatchObject({role:'translation',jobId:translatedJob.id,status:'mock',connectionId:'local-scripted'});
  expect(translated.sources).toEqual(translatedBaseline.sources);expect(translated.jobs).toEqual(translatedBaseline.jobs);expect(translated.attempts).toEqual(translatedBaseline.attempts);
});






