import { test, expect } from '@playwright/test';
import type { Content, Library } from '../core/product.js';

test('PKUI01 package editing preserves internal lore, instructions, unsaved work and cross-role copies', async ({ page, request }, info) => {
  test.setTimeout(60000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await page.getByRole('navigation', { name: '자료 탐색', exact: true }).getByRole('button', { name: '봇', exact: true }).click();
  const library = page.getByTestId('library-panel');
  await expect(library.getByRole('tab')).toHaveText(['봇', '페르소나', '모듈', '프롬프트']);
  await library.getByRole('button', { name: '새로 만들기', exact: true }).first().click();
  await library.getByLabel('자료 이름', { exact: true }).fill('Synthetic package editor bot');
  await library.getByLabel('자료 본문', { exact: true }).fill('Synthetic common body.');
  const fields = library.getByRole('region', { name: '패키지 구성', exact: true });
  await fields.getByRole('button', { name: '로어 추가', exact: true }).click();
  await fields.getByLabel('로어 1 이름', { exact: true }).fill('Synthetic harbor');
  await fields.getByLabel('로어 1 본문', { exact: true }).fill('A blue bell hangs by the synthetic harbor.');
  await fields.getByLabel('사용 방법', { exact: true }).selectOption('pinned');
  await fields.getByRole('button', { name: '지침', exact: true }).click();
  await fields.getByRole('button', { name: '지침 추가', exact: true }).click();
  await fields.getByLabel('지침 1 본문', { exact: true }).fill('Mention visible actions before interpretation.');
  await library.getByRole('button', { name: '← 서재 목록', exact: true }).click();
  const guard = library.getByRole('alertdialog', { name: '미저장 자료 확인', exact: true }); await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: '계속 편집', exact: true }).click();
  await expect(fields.getByLabel('지침 1 본문', { exact: true })).toHaveValue('Mention visible actions before interpretation.');
  await library.getByRole('button', { name: '자료 등록', exact: true }).click();
  await expect(library.getByRole('status')).toContainText('v1 저장됨');
  const listingResponse = await request.get('/api/library'); expect(listingResponse.ok()).toBe(true); const listing: Library = await listingResponse.json();
  const summary = listing.contents.find(item => item.title === 'Synthetic package editor bot')!; expect(summary).toBeTruthy();
  const fullResponse = await request.get(`/api/revisions/content/${summary.id}/${summary.revision}`); expect(fullResponse.ok()).toBe(true); const original: Content = await fullResponse.json();
  expect(original.package?.lore[0]).toMatchObject({ title: 'Synthetic harbor', text: 'A blue bell hangs by the synthetic harbor.', loading: 'pinned' });
  expect(original.package?.instructions[0]).toMatchObject({ target: 'main', text: 'Mention visible actions before interpretation.' });
  await library.getByRole('button', { name: '← 서재 목록', exact: true }).click();
  await library.getByRole('button', { name: 'Synthetic package editor bot 자료 편집', exact: true }).click();
  await expect(fields.getByLabel('로어 1 본문', { exact: true })).toHaveValue('A blue bell hangs by the synthetic harbor.');
  await fields.getByRole('button', { name: '지침', exact: true }).click();
  await expect(fields.getByLabel('지침 1 본문', { exact: true })).toHaveValue('Mention visible actions before interpretation.');
  await library.getByText('패키지 가져오기·내보내기와 역할 사본', { exact: true }).click();
  await library.getByRole('button', { name: '페르소나로 사본 만들기', exact: true }).click();
  await expect(library.getByLabel('자료 종류', { exact: true })).toHaveValue('persona');
  await expect(library.getByLabel('자료 이름', { exact: true })).toHaveValue('Synthetic package editor bot 사본');
  const afterResponse = await request.get('/api/library'); const after: Library = await afterResponse.json(); const copy = after.contents.find(item => item.kind === 'persona' && item.title === 'Synthetic package editor bot 사본')!;
  expect(copy.id).not.toBe(original.id);
  const copyResponse = await request.get(`/api/revisions/content/${copy.id}/${copy.revision}`); const copied: Content = await copyResponse.json();
  expect(copied.package?.lore).toEqual(original.package?.lore); expect(copied.package?.instructions).toEqual(original.package?.instructions); expect(copied.package?.id).toBe(copy.id);
  const unchangedResponse = await request.get(`/api/revisions/content/${original.id}/${original.revision}`); expect(await unchangedResponse.json()).toEqual(original);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath('package-editor-mobile.png') }); expect(errors).toEqual([]);
});

test('PKUI02 library exposes package roles and prompts with direct internal lore authoring', async ({ page, request }, info) => {
  const title=`Synthetic current library ${Date.now()}`;
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  const menu=page.getByRole('button',{name:'탐색 메뉴',exact:true});if(await menu.isVisible())await menu.click();
  await page.getByRole('navigation', { name: '자료 탐색', exact: true }).getByRole('button', { name: '봇', exact: true }).click();
  const library = page.getByTestId('library-panel');
  await expect(library.getByRole('tab')).toHaveText(['봇', '페르소나', '모듈', '프롬프트']);
  await expect(library.getByText('이전 자료',{exact:true})).toHaveCount(0);
  for(const name of ['로어','창작 프리셋','작가 설정','창작 스킬','명칭집'])await expect(library.getByRole('button',{name,exact:true})).toHaveCount(0);
  await library.getByRole('tab',{name:'프롬프트',exact:true}).click();await expect(library.getByTestId('prompt-editor')).toBeVisible();
  await library.getByRole('tab',{name:'봇',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:info.outputPath('package-library-mobile.png')});
  await library.getByRole('button', { name: '새로 만들기', exact: true }).first().click();
  await expect(library.getByLabel('자료 종류',{exact:true}).locator('option')).toHaveText(['봇','페르소나','모듈']);
  await expect(library.getByLabel('관련 자료 검색',{exact:true})).toHaveCount(0);
  await library.getByLabel('자료 이름', { exact: true }).fill(title);
  const fields = library.getByRole('region', { name: '패키지 구성', exact: true });
  await expect(fields.getByText('이전 자료에서 가져오기',{exact:true})).toHaveCount(0);
  await fields.getByRole('button', { name: '로어 추가', exact: true }).click();
  await fields.getByLabel('로어 1 이름', { exact: true }).fill('Direct authored lore');
  await fields.getByLabel('로어 1 본문', { exact: true }).fill('Synthetic direct lore text');
  await fields.getByRole('button', { name: '지침', exact: true }).click();
  await fields.getByRole('button', { name: '지침 추가', exact: true }).click();
  await fields.getByLabel('지침 1 본문', { exact: true }).fill('Synthetic package instruction');
  await library.getByRole('button', { name: '자료 등록', exact: true }).click();await expect(library.getByRole('status')).toContainText('v1 저장됨');
  const listing:Library=await(await request.get('/api/library')).json();const item=listing.contents.find(item=>item.title===title)!;expect(item).toBeTruthy();
  const saved:Content=await(await request.get(`/api/revisions/content/${item.id}/${item.revision}`)).json();
  expect(saved.package?.lore[0].text).toBe('Synthetic direct lore text');expect(saved.package?.instructions[0].text).toBe('Synthetic package instruction');expect(saved.relatedIds).toEqual([]);
});
