import { describe,it,expect } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { validatePackageBehavior, type PackageBehavior } from '../core/package-behavior.js';
import { PackageBehaviorStore, recordDraws, type BehaviorScope } from '../server/package-behavior-store.js';

function definition():PackageBehavior{return {
  revision:1,schemaVersion:1,stateSchema:{type:'record',properties:{hp:{type:'number',min:0,max:100,integer:true},alive:{type:'boolean'},name:{type:'string',maxLength:20},items:{type:'list',maxItems:10,items:{type:'string',maxLength:20}}}},
  initialState:{hp:10,alive:true,name:'',items:[]},
  actions:[{id:'change',inputSchema:{type:'record',properties:{hp:{type:'number',min:0,max:100},alive:{type:'boolean'}}},effects:[{path:['hp'],value:{context:['input','hp']}},{path:['alive'],value:{context:['input','alive']}}]},
    {id:'draw',inputSchema:{type:'record',properties:{}},draws:[{id:'dice',type:'integer',min:1,max:6},{id:'order',type:'shuffle',values:['a','b','c']}],effects:[{path:['hp'],value:{context:['draws','dice']}}]},
    {id:'before',inputSchema:{type:'record',properties:{}},effects:[{path:['hp'],value:0},{path:['alive'],value:{op:'typedEqual',args:[{context:['state','hp']},10]}}]}],
  outputParsers:[{id:'json',format:'json',fields:[{path:['hp'],from:['hp']},{path:['alive'],from:['alive']}]},{id:'name',format:'json',fields:[{path:['name'],from:['name']}]},{id:'delim',format:'delimited',start:'[S:',end:']',delimiter:'|',fields:[{path:['hp'],from:['0'],valueType:'number'},{path:['alive'],from:['1'],valueType:'boolean'}]}]
};}
const scope:BehaviorScope={chatId:'chat',branchId:'branch',attachmentInstanceId:'slot',packageId:'pkg',packageRevision:1,behaviorRevision:1,schemaVersion:1};
function fixture(){const db=new DatabaseSync(':memory:');let source:string|null='source';const store=new PackageBehaviorStore(db,()=>source);store.init();return {db,store,b:definition(),source:(v:string|null)=>source=v};}
const action={actionId:'change',input:{hp:0,alive:false},expectedStateRevision:0,expectedSourceHash:'source',idempotencyKey:'a'};
describe('package behavior transactions',()=>{
  it('runs the published daily-state fixture with typed inventory, costs, stable dice and a new dated schedule',()=>{
    const f=fixture();try{
      const b=validatePackageBehavior(JSON.parse(readFileSync(new URL('../fixtures/daily-state-behavior.json',import.meta.url),'utf8')));
      const spend={actionId:'spend',input:{cost:3},expectedStateRevision:0,expectedSourceHash:'source',idempotencyKey:'spend'};
      const first=f.store.execute(scope,b,spend);expect(first.state).toMatchObject({energy:7});expect(Number(first.draws.die)).toBeGreaterThanOrEqual(1);expect(Number(first.draws.die)).toBeLessThanOrEqual(6);expect(f.store.execute(scope,b,spend)).toEqual(first);
      const item=f.store.execute(scope,b,{...spend,actionId:'add-item',input:{item:'수첩'},expectedStateRevision:1,idempotencyKey:'item'});expect(item.state).toMatchObject({inventory:['수첩']});
      const next=f.store.execute(scope,b,{...spend,actionId:'next-day',input:{},expectedStateRevision:2,idempotencyKey:'next'});expect(next.state).toMatchObject({day:'2026-01-02T00:00:00.000Z',energy:10});expect((next.draws.schedule as string[]).toSorted()).toEqual(['도서관','산책','작업실','휴식'].toSorted());
    }finally{f.db.close();}
  });
  it('rolls back an action whose individually bounded effects exceed the shared action budget',()=>{
    const f=fixture();try{
      const keys=Array.from({length:100},(_,i)=>`v${i}`);
      const b=validatePackageBehavior({revision:1,schemaVersion:1,stateSchema:{type:'record',properties:Object.fromEntries(keys.map(key=>[key,{type:'number',min:0,max:1e6}]))},initialState:Object.fromEntries(keys.map(key=>[key,0])),actions:[{id:'batch',inputSchema:{type:'record',properties:{}},effects:keys.map(key=>({path:[key],value:{op:'sum',args:[{op:'range',args:[0,1000]}]}}))}],outputParsers:[]});
      expect(()=>f.store.execute(scope,b,{...action,actionId:'batch',input:{}})).toThrow('PROMPT_STEP_LIMIT');expect(f.store.read(scope,b).stateRevision).toBe(0);expect(f.store.journal(scope)).toEqual([]);
    }finally{f.db.close();}
  });
  it('records host context but uses authoritative state/input/draws and replays the original host projection',()=>{const f=fixture();try{f.b.actions[0].when={context:['options','enabled']};const runtime={options:{enabled:true},state:{hp:99},input:{hp:88},draws:{dice:999}};const r=f.store.execute(scope,f.b,action,runtime);expect(r.state).toMatchObject({hp:0,alive:false});expect(f.store.execute(scope,f.b,action,{options:{enabled:false}})).toEqual(r);}finally{f.db.close();}});
  it('skips only completely absent optional marker pairs and rejects partial or malformed optional output',()=>{const f=fixture();try{f.b.outputParsers[2].required=false;const c={parserId:'delim',text:'ordinary prose',baseStateRevision:0,sourceHash:'source',idempotencyKey:'optional'};expect(f.store.applyOutput(scope,f.b,c).state).toEqual(f.b.initialState);expect(()=>f.store.applyOutput(scope,f.b,{...c,baseStateRevision:1,text:'[S:1',idempotencyKey:'partial'})).toThrow('MARKER');expect(()=>f.store.applyOutput(scope,f.b,{...c,baseStateRevision:1,text:'[S:no|maybe]',idempotencyKey:'malformed'})).toThrow();}finally{f.db.close();}});
  it('evaluates all effects against the same before state',()=>{const f=fixture();try{expect(f.store.execute(scope,f.b,{...action,actionId:'before',input:{}}).state).toMatchObject({hp:0,alive:true});}finally{f.db.close();}});
  it('resets explicitly with source/state CAS and records its before state',()=>{const f=fixture();try{f.store.execute(scope,f.b,action);const c={expectedStateRevision:1,expectedSourceHash:'source',idempotencyKey:'reset'};const r=f.store.reset(scope,f.b,c);expect(r.state).toEqual(f.b.initialState);expect(r.beforeState).toMatchObject({hp:0,alive:false});expect(r.provenance).toBe('explicit-reset');expect(f.store.reset(scope,f.b,c)).toEqual(r);}finally{f.db.close();}});
  it('reads and previews defaults without rows or draws; preserves zero and false',()=>{const f=fixture();try{expect(f.store.read(scope,f.b).stateRevision).toBe(0);expect(f.store.preview(scope,f.b,action).projectedState).toMatchObject({hp:0,alive:false});expect(f.store.preview(scope,f.b,{actionId:'draw',input:{}}).requiresDraw).toBe(true);expect(f.db.prepare('SELECT count(*) n FROM package_behavior_states').get()?.n).toBe(0);const r=f.store.execute(scope,f.b,action);expect(r.state).toMatchObject({hp:0,alive:false});expect(r.beforeState).toMatchObject({hp:10,alive:true});expect(r.beforeStateRevision).toBe(0);}finally{f.db.close();}});
  it('replays identical payload, conflicts on changed input and rejects stale revisions/source',()=>{const f=fixture();try{const r=f.store.execute(scope,f.b,action);expect(f.store.execute(scope,f.b,action)).toEqual(r);expect(()=>f.store.execute(scope,f.b,{...action,input:{hp:1,alive:false}})).toThrow('IDEMPOTENCY_CONFLICT');expect(()=>f.store.execute(scope,f.b,{...action,idempotencyKey:'b'})).toThrow('STATE_STALE');f.source('edited');expect(()=>f.store.execute(scope,f.b,{...action,expectedStateRevision:1,idempotencyKey:'c'})).toThrow('SOURCE_STALE');expect(f.store.journal(scope)).toHaveLength(1);}finally{f.db.close();}});
  it('journals host seed and draw results and reuses them',()=>{const f=fixture();try{const c={...action,actionId:'draw',input:{}};const r=f.store.execute(scope,f.b,c);expect(r.drawSeed).toMatch(/^[a-f0-9]{64}$/);expect(r.draws).toEqual(recordDraws(f.b.actions[1].draws!,r.drawSeed!));expect([...r.draws.order as string[]].sort()).toEqual(['a','b','c']);expect(f.store.execute(scope,f.b,c)).toEqual(r);}finally{f.db.close();}});
  it('checks conditions and validates whole next state before saving any effect',()=>{const f=fixture();try{f.b.actions[0].when=false;expect(()=>f.store.execute(scope,f.b,action)).toThrow('DISABLED');f.b.actions[0].when=true;f.b.actions[0].effects[1].value='bad';expect(()=>f.store.execute(scope,f.b,action)).toThrow('BOOLEAN_VALUE');expect(f.store.read(scope,f.b).stateRevision).toBe(0);expect(f.store.journal(scope)).toEqual([]);}finally{f.db.close();}});
  it('applies grouped output fields atomically with distinct provenance and late-result rejection',()=>{const f=fixture();try{const c={parserIds:['json','name'],text:'{"hp":0,"alive":false,"name":12}',baseStateRevision:0,sourceHash:'source',idempotencyKey:'out'};expect(()=>f.store.applyOutputs(scope,f.b,c)).toThrow('STRING_VALUE');expect(f.store.journal(scope)).toHaveLength(0);const r=f.store.applyOutputs(scope,f.b,{...c,text:'{"hp":0,"alive":false,"name":"N"}'});expect(r.provenance).toBe('local-output-parser');expect(r.state).toMatchObject({hp:0,alive:false,name:'N'});expect(()=>f.store.applyOutputs(scope,f.b,{...c,idempotencyKey:'late'})).toThrow('STATE_STALE');}finally{f.db.close();}});
  it('parses fixed delimiters, refuses extra markers, unsafe data and overlapping parser destinations',()=>{const f=fixture();try{expect(f.store.applyOutput(scope,f.b,{parserId:'delim',text:'story [S:0|false]',baseStateRevision:0,sourceHash:'source',idempotencyKey:'d'}).state).toMatchObject({hp:0,alive:false});expect(()=>f.store.applyOutput(scope,f.b,{parserId:'delim',text:'[S:1|true][S:2|true]',baseStateRevision:1,sourceHash:'source',idempotencyKey:'bad'})).toThrow('MARKER');expect(()=>f.store.applyOutputs(scope,f.b,{parserIds:['json','delim'],text:'{}',baseStateRevision:1,sourceHash:'source',idempotencyKey:'over'})).toThrow('OVERLAPPING');expect(()=>f.store.applyOutput(scope,f.b,{parserId:'json',text:'{"__proto__":{},"hp":1,"alive":true}',baseStateRevision:1,sourceHash:'source',idempotencyKey:'proto'})).toThrow('UNSAFE');}finally{f.db.close();}});
  it('requires explicit migration for any definition revision change at a stable instance',()=>{const f=fixture();try{f.store.ensure(scope,f.b);expect(()=>f.store.read({...scope,packageRevision:2},f.b)).toThrow('MIGRATION_REQUIRED');const newer={...f.b,revision:2};expect(()=>f.store.read({...scope,behaviorRevision:2},newer)).toThrow('MIGRATION_REQUIRED');expect(()=>f.store.migrate()).toThrow('NOT_IMPLEMENTED');}finally{f.db.close();}});
  it('joins host transactions so later host failure rolls state and journal back',()=>{const f=fixture();try{f.db.exec('BEGIN');f.store.executeInTransaction(scope,f.b,action);f.db.exec('ROLLBACK');expect(f.store.read(scope,f.b).stateRevision).toBe(0);expect(f.store.journal(scope)).toHaveLength(0);}finally{f.db.close();}});
  it('fork copies isolated state and does not reuse the original idempotency namespace',()=>{const f=fixture();try{f.store.execute(scope,f.b,action);f.db.exec('BEGIN');f.store.cloneBranchInTransaction('chat','branch','fork-chat','fork');f.db.exec('COMMIT');const fork={...scope,chatId:'fork-chat',branchId:'fork'};expect(f.store.read(fork,f.b).stateRevision).toBe(1);f.store.execute(fork,f.b,{...action,expectedStateRevision:1,input:{hp:20,alive:true}});expect(f.store.read(scope,f.b).state).toMatchObject({hp:0});}finally{f.db.close();}});
  it('validates nested state bounds and rejects prototype-bearing records without mutating input',()=>{const b=definition();const original=structuredClone(b);validatePackageBehavior(b);expect(b).toEqual(original);b.initialState=Object.create({hp:1});expect(()=>validatePackageBehavior(b)).toThrow(/EXPECTED_RECORD|INVALID_RUNTIME_VALUE/);const bad=definition();bad.actions[0].effects[0].path=['constructor'];expect(()=>validatePackageBehavior(bad)).toThrow('INVALID_ID');});
});
