export type Settings = { preset: 'calm' | 'vivid'; mode: 'direct' | 'research'; translation: boolean; status: boolean; maxCalls: number };
export type Chat = { id: string; title: string; headRevision: string | null; settingsRevision: number; settings: Settings; botId?: string; folderId?: string | null; organizationRevision?: number };
export type Resource = { loreContext?: import('./lore-context.js').LorePlacement; id: string; chatId: string; kind: 'lore' | 'skill'; revision: number; title: string; description: string; text: string; sourceKind?: string; loading?: 'pinned' | 'discoverable'; relatedIds?: string[] };
export type ModelInput = { role: 'main'; contract: string; task: string; preset: Settings['preset']; facts: string[]; history: { revision: string; text: string; contentHash?: string }[]; catalog: Omit<Resource, 'text' | 'chatId'>[]; prefetch: string[]; tools: string[]; results: ToolEvent[] };
export type ToolEvent = { callId: string; name: string; args: Record<string, unknown>; result: unknown; denied: boolean };
export type Usage = { modelCalls: number; inputTokens: number | null; outputTokens: number | null; costUsd: number | null };
export type RunSnapshot = { loreContext?: import('./lore-context.js').LoreContextSnapshot; loreContextReset?: boolean; forkedLoreReads?: import('./lore-context.js').ForkedLoreReads; packageStart?: import("./package-start.js").PackageStartSnapshot; behaviorExecution?: import('./behavior-execution.js').BehaviorRunSnapshot; executionClock?: { iso: string; unix: number }; packageStates?: import('./execution-context.js').PackageExecutionState[]; nativeBot?: import('./native-bot.js').NativeBotSnapshot; hiddenStory?: import('./hidden-story-package.js').HiddenStoryRunSnapshot; logicalHistory?: import('./prompt-program.js').PromptHistoryMessage[]; promptCompilation?: import('./prompt-program.js').PromptCompilation; chatId: string; parentRevision: string | null; settingsRevision: number; settings: Settings; request: string; history: { revision: string; text: string; contentHash?: string }[]; resources: Resource[]; branchId?: string; profile?: import('./product.js').ProfileSnapshot; candidateOf?: string; forkedFrom?: { chatId: string; runId: string; sourceRevision: string }; story?: import('./story.js').StorySnapshot };
export type Run = { id: string; chatId: string; parentRevision: string | null; settingsRevision: number; snapshot: RunSnapshot; request: string; status: 'queued' | 'running' | 'waiting_for_state' | 'completed' | 'failed' | 'cancelled' | 'interrupted' | 'refused' | 'partial'; sourceRevision: string | null; error: string | null; usage: Usage; inputs: ModelInput[]; toolEvents: ToolEvent[]; partialText?: string; issue?: string | null };
export type Source = { editRevision?: number; translationRevision?: number; id: string; chatId: string; parentRevision: string | null; runId: string; text: string; hash: string; blocks?: { anchor: string; index: number; text: string; start: number; end: number }[] };
export type Job = { id: string; chatId: string; sourceRevision: string; sourceHash: string; kind: 'translation' | 'status' | 'image'; status: 'queued' | 'running' | 'completed' | 'failed' | 'stale' | 'partial' | 'cancelled' | 'interrupted'; attempt: number; error: string | null; result: { mock: boolean; manual?: boolean; text?: string; label?: string; sourceRevision: string; sourceHash: string; blocks?: { anchor: string; text: string }[]; segments?: { anchors: string[]; text: string }[]; annotations?: { blockAnchor: string; assetRef: string; assetRevision: number; assetHash: string; presentationIntent: "profile" | "inline"; caption?: string }[] } | null; chunks?: { id: string; status: string; attempt: number; error: string | null; result?: unknown }[]; revision?: number };
export type ChatDetail = { chat: Chat; runs: Run[]; sources: Source[]; jobs: Job[]; profile?: import('./product.js').ChatProfile; branches?: import('./product.js').Branch[]; attempts?: import('./product.js').Attempt[]; assets?: import('./product.js').Asset[] };

/** Reader summaries never stand in for frozen execution inputs. */
export type ReaderRun = Omit<Run, 'snapshot'|'inputs'|'toolEvents'> & { snapshot: Pick<RunSnapshot,'branchId'|'candidateOf'|'forkedFrom'>; modelTitle?:string;packageStart?: Pick<import("./package-start.js").PackageStartSnapshot,"mode"|"title">;hasPackages?:boolean;hiddenConfig?:import('./hidden-story.js').HiddenStoryConfig };
export type ReaderDetail = Omit<ChatDetail,'runs'|'attempts'> & { runs:ReaderRun[]; reader:{nativeBotAttached?:boolean;headSourceHash?:string|null;activeJobs:number;cursor:number;order:string[];start:number;total:number;previous:string|null;next:string|null;latest:string|null;projection:true} };
