import { runBrowserVerification } from './browser-verification.mjs';

await runBrowserVerification({
  name: 'library',
  scope:
    'Library folders, role selection, portraits, prompt management and guarded deletion synthetic browser regression',
  providerFixture: true,
  files: [
    'tests/library-browser.spec.ts',
    'tests/library-compact-browser.spec.ts',
    'tests/library-images-browser.spec.ts',
    'tests/package-features-browser.spec.ts',
    'tests/shared-package-browser.spec.ts',
    'tests/new-story-browser.spec.ts',
    'tests/package-editor-browser.spec.ts',
    'tests/package-navigation-browser.spec.ts',
    'tests/lore-context-browser.spec.ts',
    'tests/edit-drafts-browser.spec.ts',
    'tests/deletion-browser.spec.ts',
  ],
  requiredCases: [
    'LIBUI01',
    'LIBUI02',
    'LIBUI03',
    'LIBUI04',
    'LIBUI05',
    'LIBUI06',
    'LCOM01',
    'LCOM02',
    'LCOM03',
    'LIMG01',
    'LIMG02',
    'LIMG03',
    'LIMG04',
    'LIMG05',
    'DEL01',
    'NSUI01',
    'PKUI01',
    'PKUI03',
    'PKUI04',
    'PNAV01',
    'PNAV02',
    'PNAV03',
    'LCUI01',
    'LCUI02',
    'ED01',
    'ED02',
  ],
});
