import { DeleteButton } from './DeleteButton.js';
import { useEffect, useRef, useState } from 'react';
import type { ChatProfile } from '../core/product.js';
import { defaultHiddenStoryConfig, hiddenConfigIssues, validateHiddenStoryConfig } from '../core/hidden-story.js';
import type { HiddenStoryNativePackage, HiddenStorySelection } from '../core/hidden-story-package.js';
import { api } from './api.js';

type Props={profile:ChatProfile & {hiddenStory?:HiddenStorySelection};forceNonsexual?:boolean;onChanged:()=>void;onError:(message:string)=>void};
const key=(value:{id:string;revision:number}|null)=>value?`${value.id}@${value.revision}`:'';
export function HiddenStoryPanel(props:Props){return <Editor key={`${props.profile.chatId}/${props.profile.revision}`} {...props}/>;}
function Editor({profile,forceNonsexual=false,onChanged,onError}:Props){
  const [modules,setModules]=useState<HiddenStoryNativePackage[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [draft,setDraft]=useState<HiddenStorySelection>(()=>structuredClone(profile.hiddenStory??{module:null,config:defaultHiddenStoryConfig(forceNonsexual?'nonsexual':'general-fiction'),insertion:'before-current'}));
  const alive=useRef(true),lock=useRef(false);
  useEffect(()=>{alive.current=true;api<HiddenStoryNativePackage[]>('/hidden-story/modules').then(async result=>{if(profile.hiddenStory?.module&&!result.some(m=>key(m)===key(profile.hiddenStory!.module))){const r=profile.hiddenStory.module;result.push(await api<HiddenStoryNativePackage>(`/hidden-story/modules/${encodeURIComponent(r.id)}?revision=${r.revision}`));}if(alive.current)setModules(result);}).catch(error=>{if(alive.current)onError(String(error));});return()=>{alive.current=false;};},[]);
  const selected=modules.find(m=>key(m)===key(draft.module));
  const act=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await work();}catch(error){if(alive.current)onError(error instanceof Error?error.message:String(error));}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const effective={...draft.config,contentPolicy:forceNonsexual?'nonsexual' as const:draft.config.contentPolicy};
  let issues:string[]=[];try{issues=hiddenConfigIssues(validateHiddenStoryConfig(effective));}catch(error){issues=[error instanceof Error?error.message:String(error)];}
  return <section className="story-panel" aria-label="히든 스토리 모듈"><h3>히든 스토리</h3><p className="muted">본문 사이에 다른 시점의 이야기를 배치해요. 독자가 펼쳐 읽어도 등장인물이 그 정보를 알게 되지는 않아요.</p>
    <label>로컬 네이티브 모듈 가져오기<input type="file" accept="application/json,.json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;void act(async()=>{if(file.size>1_000_000)throw new Error('1MB 이하의 네이티브 JSON을 선택해 주세요.');const conversion=JSON.parse(await file.text());if(!alive.current)return;const module=await api<HiddenStoryNativePackage>('/hidden-story/modules',{title:conversion.source?.name??file.name,conversion});if(!alive.current)return;setModules(await api<HiddenStoryNativePackage[]>('/hidden-story/modules'));if(alive.current){setDraft(d=>({...d,module:{id:module.id,revision:module.revision}}));setMessage('모듈을 가져왔어요. 적용하면 이 대화에 연결돼요.');}});}}/></label>
    <label>이 대화의 모듈<select disabled={busy} value={key(draft.module)} onChange={event=>{const module=modules.find(m=>key(m)===event.target.value);setDraft(d=>({...d,module:module?{id:module.id,revision:module.revision}:null}));}}><option value="">사용 안 함</option>{draft.module&&!selected&&<option value={key(draft.module)}>보관된 선택 · v{draft.module.revision}</option>}{modules.map(module=><option key={key(module)} value={key(module)}>{module.title} · v{module.revision}</option>)}</select></label>
    {selected&&<DeleteButton path={`/hidden-story/modules/${encodeURIComponent(selected.id)}`} revision={selected.revision} title={selected.title} label="모듈 삭제" disabled={busy} onError={onError} onDeleted={async()=>{setModules(items=>items.filter(item=>item.id!==selected.id));setDraft(d=>({...d,module:null}));onChanged();}}/>}
    <label>요청 안의 삽입 위치<select disabled={busy} value={draft.insertion??'before-current'} onChange={event=>setDraft(d=>({...d,insertion:event.target.value as HiddenStorySelection['insertion']}))}><option value="before-current">현재 요청 직전</option><option value="before-history">대화 기록 앞</option></select></label>
    {forceNonsexual?<p>연결된 캐릭터에 맞춰 비성적 창작만 허용돼요.</p>:<label>창작 범위<select disabled={busy} value={draft.config.contentPolicy} onChange={event=>setDraft(d=>({...d,config:{...d.config,contentPolicy:event.target.value as typeof d.config.contentPolicy}}))}><option value="general-fiction">일반 창작</option><option value="nonsexual">비성적 창작</option></select></label>}
    {selected&&<details><summary>원본에서 옮긴 제어 35개</summary><div className="form-grid">{selected.program.controls.map(control=><label key={control.id}>{control.label}{control.type==='boolean'?<input type="checkbox" disabled={busy} checked={effective.values[control.id as keyof typeof effective.values]===true} onChange={event=>setDraft(d=>({...d,config:{...d.config,values:{...d.config.values,[control.id]:event.target.checked}}}))}/>:control.type==='select'?<select disabled={busy} value={String(effective.values[control.id as keyof typeof effective.values])} onChange={event=>{const value=control.options?.find(o=>String(o.value)===event.target.value)?.value;setDraft(d=>({...d,config:{...d.config,values:{...d.config.values,[control.id]:value!}}}));}}>{control.options?.map(option=><option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</select>:<input disabled={busy} value={String(effective.values[control.id as keyof typeof effective.values])} onChange={event=>setDraft(d=>({...d,config:{...d.config,values:{...d.config.values,[control.id]:event.target.value}}}))}/>}</label>)}</div></details>}
    {issues.length>0&&<details><summary>변경·미지원 항목 {issues.length}개</summary><ul>{issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul></details>}
    {selected&&<p className="muted">원본 depth는 기록으로 보존해요. 실제 삽입은 위에서 고른 위치에서 system 조각별 순서를 유지해요.</p>}
    <button disabled={busy} onClick={()=>void act(async()=>{const selection={...draft,config:validateHiddenStoryConfig(effective)};await api(`/chats/${encodeURIComponent(profile.chatId)}/hidden-story`,{expectedRevision:profile.revision,selection},'PUT');if(alive.current){setMessage('히든 스토리 설정을 적용했어요.');onChanged();}})}>이 대화에 적용</button>{message&&<p role="status">{message}</p>}
  </section>;
}
