import { DeleteButton } from './DeleteButton.js';
import { useEffect, useRef, useState } from 'react';
import type { NativeBotPackage, NativeBotSnapshot, NativeCommandInput, NativeAxis } from '../core/native-bot.js';
import { api } from './api.js';
export type NativeBotPanelProps={chatId:string;branchId:string;headRevision:string|null;sourceHash?:string|null;refreshKey?:unknown;onChanged:()=>void;onError:(message:string)=>void;onRunRequest?:(text:string,commandId?:string)=>void};
export function NativeBotPanel(props:NativeBotPanelProps) { return <NativeBotEditor key={`${props.chatId}/${props.branchId}`} {...props}/>; }
function StatControl({field,label,value,disabled,apply}:{field:NativeAxis;label:string;value:number;disabled:boolean;apply:(command:NativeCommandInput)=>void}) {
  const [draft,setDraft]=useState(String(value)); const parsed=Number(draft); const valid=draft.trim()!==''&&Number.isFinite(parsed)&&parsed!==value;
  return <form onSubmit={event=>{event.preventDefault();if(valid&&!disabled)apply({kind:'set-stat',field,value:parsed});}}><label>{label}<input type="number" step="any" value={draft} disabled={disabled} onChange={event=>setDraft(event.target.value)}/></label><button type="submit" disabled={disabled||!valid}>{label} 적용</button><small>1–100 범위에 맞춰 저장해요.</small></form>;
}
function NativeBotEditor({chatId,branchId,headRevision,sourceHash:onScreenHash,refreshKey,onChanged,onError,onRunRequest}:NativeBotPanelProps) {
  const [packages,setPackages]=useState<NativeBotPackage[]>([]); const [current,setCurrent]=useState<NativeBotSnapshot|null>(null); const [selected,setSelected]=useState(''); const [busy,setBusy]=useState(false); const [ready,setReady]=useState(false); const [time,setTime]=useState(''); const [loreQuery,setLoreQuery]=useState(''); const [loreGroup,setLoreGroup]=useState(''); const [outfit,setOutfit]=useState('');
  const inFlight=useRef(false); const sourceHash=headRevision===null?null:onScreenHash??(current?.sourceRevision===headRevision?current.sourceHash:null);
  const generation=useRef(0); const alive=useRef(true); const path=`/chats/${encodeURIComponent(chatId)}/native-bot`; const scopeKey=`${headRevision}:${onScreenHash}`;const head=useRef(scopeKey); if(head.current!==scopeKey) {head.current=scopeKey;generation.current++;}
  const refresh=useRef(refreshKey);if(!Object.is(refresh.current,refreshKey)){refresh.current=refreshKey;generation.current++;}
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;};},[]);
  const valid=(g:number)=>alive.current&&generation.current===g;
  useEffect(()=>{const g=++generation.current;inFlight.current=false;setBusy(false);setReady(false);Promise.all([api<NativeBotPackage[]>('/native-bots'),api<NativeBotSnapshot|null>(`${path}?branchId=${encodeURIComponent(branchId)}`)]).then(([list,value])=>{if(!valid(g))return;setPackages(list);setCurrent(value);setSelected(value?.package.id??list[0]?.id??'');setReady(true);}).catch(error=>{if(valid(g))onError(String(error.message??error));});},[chatId,branchId,headRevision,onScreenHash,refreshKey]);
  const guard=()=>({branchId,expectedRevision:current?.revision??0,expectedSourceRevision:headRevision,expectedSourceHash:sourceHash,idempotencyKey:crypto.randomUUID()});
  async function act(body:Record<string,unknown>,attach=false) {if(inFlight.current||!ready||headRevision!==null&&!sourceHash)return;const g=generation.current;inFlight.current=true;setBusy(true);try {const result=await api<NativeBotSnapshot>(attach?path:`${path}/commands`,{...guard(),...body},attach?'PUT':'POST');if(valid(g)){setCurrent(result);onChanged();}}catch(error){if(valid(g))onError((error as Error).message);}finally{if(valid(g)){inFlight.current=false;setBusy(false);}}}
  async function importFile(file:File) {if(inFlight.current)return;const g=generation.current;inFlight.current=true;setBusy(true);try{if(file.size>2_000_000)throw new Error('패키지 JSON은 2 MB 이하여야 해요.');const value=JSON.parse(await file.text());if(!valid(g))return;const result=await api<NativeBotPackage>('/native-bots',value);if(valid(g)){setPackages(list=>[...list.filter(p=>p.id!==result.id),result]);setSelected(result.id);}}catch(error){if(valid(g))onError((error as Error).message);}finally{if(valid(g)){inFlight.current=false;setBusy(false);}}}
  const command=(command:NativeCommandInput)=>void act({command}); const state=current?.state; const p=current?.package; const lang=state?.language??'kr';
  return <section className="story-panel" aria-label="네이티브 봇"><h2>네이티브 봇</h2><p className="muted">일상 장면과 상태를 직접 관리해요. 장면을 선택하면 다음 요청으로 예약돼요.</p>
    <label>패키지 JSON 가져오기<input type="file" accept="application/json,.json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void importFile(file);event.target.value='';}}/></label>
    <label>사용할 패키지<select value={selected} disabled={busy} onChange={event=>setSelected(event.target.value)}><option value="">패키지를 선택하세요</option>{packages.map(x=><option key={x.id} value={x.id}>{x.title} · v{x.revision}</option>)}</select></label>
    <button type="button" disabled={busy||!ready||!selected||headRevision!==null&&!sourceHash} onClick={()=>{const item=packages.find(x=>x.id===selected);if(item)void act({packageId:item.id,packageRevision:item.revision},true);}}>이 분기에 적용 · 설정 초기화</button>
    {packages.filter(item=>item.id===selected).map(item=><DeleteButton key={item.id} path={`/native-bots/${encodeURIComponent(item.id)}`} revision={item.revision} title={item.title} label="패키지 삭제" disabled={busy} onError={onError} onDeleted={async()=>{setPackages(items=>items.filter(p=>p.id!==item.id));setSelected('');onChanged();}}/>)}
    {p&&state&&<><h3>{p.title}</h3><small>{p.provenance.mode==='synthetic'?'합성 예제':'비성적 일상으로 재구성'} · 설정 v{current!.revision}</small><div className="story-state-values">{(['affection','trust','independence'] as NativeAxis[]).map((field,i)=><StatControl key={`${field}:${state[field]}:${current!.revision}`} field={field} label={['친밀도','신뢰도','자립도'][i]} value={state[field]} disabled={busy} apply={command}/>)}</div>
    <label>언어<select value={state.language} disabled={busy} onChange={event=>command({kind:'language',value:event.target.value as typeof state.language})}><option value="kr">한국어</option><option value="en">English</option><option value="jp">日本語</option></select></label>
    <label>응답 길이<select value={state.volume} disabled={busy} onChange={event=>command({kind:'volume',value:event.target.value as typeof state.volume})}><option value="standard">기본</option><option value="long">길게</option><option value="extra">아주 길게</option></select></label>
    <h3>시작 장면</h3><div className="form-actions">{p.scenes.map(scene=><button type="button" key={scene.id} disabled={busy} aria-pressed={state.sceneId===scene.id} onClick={()=>command({kind:'scene',id:scene.id})}>{scene.title[lang]}</button>)}<button type="button" disabled={busy} onClick={()=>command({kind:'back'})}>장면 선택으로 돌아가기</button></div>
    {state.sceneId&&(()=>{const scene=p.scenes.find(s=>s.id===state.sceneId);const asset=p.assets.find(a=>a.id===scene?.assetId);return asset?<figure><svg role="img" aria-label="합성 일상 심볼" width="180" height="110" viewBox="0 0 180 110"><rect width="180" height="110" rx="18" fill={asset.color}/><text x="90" y="65" textAnchor="middle" fill="white" fontSize="25">{asset.symbol}</text></svg><figcaption>{scene?.title[lang]} · 합성 이미지</figcaption></figure>:null;})()}
    <h3>다음 대화 제안</h3><div className="form-actions">{p.actions.map(action=>{const locked=Object.entries(action.requires).some(([k,v])=>state[k as NativeAxis]<v);return <button type="button" key={action.id} disabled={busy||locked} title={locked?Object.entries(action.requires).map(([k,v])=>`${k} ≥ ${v}`).join(', '):undefined} onClick={()=>command({kind:'action',id:action.id})}>{action.title[lang]}{locked?' · 잠김':''}</button>;})}</div>
    <label>시간 경과 제안<input value={time} maxLength={500} onChange={event=>setTime(event.target.value)}/></label><button type="button" disabled={busy||!time.trim()} onClick={()=>command({kind:'time-skip',text:time})}>시간 경과 예약</button>
    {current!.pending&&<aside><strong>예약: {current!.pending.label}</strong><p>{current!.pending.request}</p>{onRunRequest&&<button type="button" disabled={busy} onClick={()=>onRunRequest(current!.pending!.request,current!.pending!.commandId)}>작성란에 넣기</button>}<button type="button" disabled={busy} onClick={()=>command({kind:'clear-pending'})}>예약 취소</button></aside>}
    <details><summary>자료 탐색 · {p.lore.filter(l=>l.kind==='entry').length}개 본문</summary><label>자료 검색<input value={loreQuery} onChange={event=>setLoreQuery(event.target.value)}/></label><label>자료 그룹<select value={loreGroup} onChange={event=>setLoreGroup(event.target.value)}><option value="">모든 그룹</option>{p.lore.filter(l=>l.kind==='group').map(l=><option value={l.id} key={l.id}>{l.title}</option>)}</select></label>{p.lore.filter(l=>l.kind==='entry'&&(!loreGroup||l.groupId===loreGroup)&&(!loreQuery||`${l.title} ${l.text}`.toLocaleLowerCase().includes(loreQuery.toLocaleLowerCase()))).map(l=><details key={l.id}><summary>{l.title} · {l.loading==='pinned'?'항상 포함':'필요할 때 조회'}</summary><p>{l.text}</p><small>관련 자료: {l.relatedIds.map(id=>p.lore.find(x=>x.id===id)?.title??id).join(', ')}</small></details>)}</details>
    <details><summary>합성 이미지 목록 · {p.assets.length}개</summary><label>상황<select value={outfit} onChange={event=>setOutfit(event.target.value)}><option value="">모든 상황</option>{[...new Set(p.assets.map(a=>a.outfit))].map(value=><option key={value}>{value}</option>)}</select></label><ul>{p.assets.filter(a=>!outfit||a.outfit===outfit).map(a=><li key={a.id}><span style={{color:a.color}}>{a.symbol}</span> · {a.outfit} / {a.emotion} · {a.id}</li>)}</ul></details>
    <details><summary>이식 범위와 제외 항목</summary><p>{p.provenance.label}</p><ul>{p.provenance.excluded.map(x=><li key={x}>{x}</li>)}</ul></details></>}
  </section>;
}
