import { useState } from 'react';
import { VERTEX_GEMINI_MODEL_ID, VERTEX_GEMINI_MAX_OUTPUT_TOKENS, type Connection, type Library, type ModelPreset, type ProviderProtocol } from '../core/product.js';
import { api } from './api.js';
import { defaultSolOptions, SOL_GATEWAYS, type SolOptions } from '../core/sol-config.js';

const ref = (item: { id:string; revision:number }) => `${item.id}@${item.revision}`;
const labels: Record<ProviderProtocol,string> = { 'sol-responses-v1':'Sol · Responses', 'fixture-sse-v1':'로컬 fixture · 검사용', 'vertex-gemini-v1':'Vertex AI · Gemini 3.8 Flash', 'openai-responses-v1':'OpenAI · Responses', 'anthropic-messages-v1':'Anthropic · Messages', 'vercel-chat-v1':'Vercel AI Gateway', 'openai-chat-v1':'OpenAI 호환 · 별도 공급자' };
const roots: Record<ProviderProtocol,string> = { 'sol-responses-v1':SOL_GATEWAYS[0].endpoint, 'fixture-sse-v1':'', 'vertex-gemini-v1':'', 'openai-responses-v1':'https://api.openai.com/v1', 'anthropic-messages-v1':'https://api.anthropic.com/v1', 'vercel-chat-v1':'https://ai-gateway.vercel.sh/v1', 'openai-chat-v1':'' };
const credentials: Record<ProviderProtocol,string> = { 'sol-responses-v1':SOL_GATEWAYS[0].credentialEnv, 'fixture-sse-v1':'', 'vertex-gemini-v1':'', 'openai-responses-v1':'NARRATIVE_PROVIDER_OPENAI', 'anthropic-messages-v1':'NARRATIVE_PROVIDER_ANTHROPIC', 'vercel-chat-v1':'NARRATIVE_PROVIDER_VERCEL', 'openai-chat-v1':'NARRATIVE_PROVIDER_CUSTOM' };
export function ConnectionEditor({ library, reload, onError }: { library:Library; reload:()=>Promise<void>; onError:(error:string)=>void }) {
  const [connection,setConnection] = useState({title:'',protocol:'fixture-sse-v1' as ProviderProtocol,endpoint:'',credentialEnv:'',enabled:false,requestTier:'flex' as 'standard'|'flex'});
  const [model,setModel] = useState({title:'',connectionRef:'',modelId:'',maxOutputTokens:8192,temperature:'',thinkingLevel:'MEDIUM' as NonNullable<ModelPreset['thinkingLevel']>,timeoutSeconds:300,structuredOutput:'default',reasoningEffort:'',thinkingMode:'',thinkingBudgetTokens:2048});
  const [busy,setBusy] = useState(false); const [message,setMessage] = useState(''); const [error,setError] = useState('');
  const [sol,setSol] = useState<SolOptions>(defaultSolOptions);
  const [solGateway,setSolGateway] = useState<typeof SOL_GATEWAYS[number]['id'] | 'local'>('vercel');
  const chosen = library.connections.find(item => ref(item) === model.connectionRef);
  const vertexConnection = connection.protocol === 'vertex-gemini-v1'; const vertexModel = chosen?.protocol === 'vertex-gemini-v1';
  const anthropic = chosen?.protocol === 'anthropic-messages-v1'; const fixture = chosen?.protocol === 'fixture-sse-v1';
  const solConnection = connection.protocol === 'sol-responses-v1'; const solModel = chosen?.protocol === 'sol-responses-v1';
  const endpointLabel = vertexConnection ? 'Vertex endpoint' : connection.protocol === 'fixture-sse-v1' ? '로컬 endpoint' : 'API 기본 주소';
  const official = ['openai-responses-v1','anthropic-messages-v1','vercel-chat-v1'].includes(connection.protocol) || (solConnection && solGateway !== 'local');
  async function perform(work:()=>Promise<void>) { setBusy(true); onError(''); setError(''); setMessage(''); try { await work(); await reload(); } catch (caught) { const detail = (caught as Error).message; setError(detail); onError(detail); await reload().catch(()=>undefined); } finally { setBusy(false); } }
  return <section className="connection-editor" data-testid="connection-editor" aria-label="연결과 모델">
    <div className="connection-notice"><strong>사용할 공급자와 모델을 한 번 저장하세요</strong><p>새 이야기에서 메인과 번역 모델을 선택할 수 있어요. 인증 값은 서버 환경변수에 두고 여기에는 그 이름만 저장해요.</p><p>Vertex의 요청 수·금액 한도는 서버에서 관리해요. 다른 공급자는 사용량을 기록하며 금액은 미확인으로 표시해요.</p></div>
    <div className="connection-list">{library.connections.map(item=><article className="compact-card" key={ref(item)}><strong>{item.title}</strong><small>{labels[item.protocol]}{item.protocol === 'vertex-gemini-v1' ? ` · ${item.requestTier === 'flex' ? 'Flex' : 'Standard'} (서버 설정 우선)` : ''} · {item.enabled ? '사용 허용':'비활성'}</small><code>{item.endpoint}</code>{item.protocol === 'vertex-gemini-v1' && <small>로컬 지원 목록이에요. 공급자 조회나 인증 확인은 하지 않아요.</small>}{item.catalogError && <p className="error">모델 목록을 확인하지 못했어요. 기존 목록과 수동 모델 ID는 유지해요.</p>}<button type="button" className="secondary" disabled={busy} onClick={()=>{void perform(async()=>{await api(`/connections/${item.id}/catalog`,{});setMessage(item.protocol === 'vertex-gemini-v1' ? '로컬 지원 모델 목록 확인 완료 · 공급자 조회 없음':'모델 목록 조회 완료');});}}>{item.protocol === 'vertex-gemini-v1' ? '로컬 지원 모델 확인':'모델 목록 새로고침'}</button></article>)}</div>
    <form className="editor-grid" onSubmit={event=>{event.preventDefault();void perform(async()=>{const created=await api<Connection>('/connections',{title:connection.title,protocol:connection.protocol,endpoint:connection.endpoint,...(connection.credentialEnv.trim()?{credentialEnv:connection.credentialEnv.trim()}:{}),...(vertexConnection?{requestTier:connection.requestTier}:{}),enabled:connection.enabled});setMessage(created.title+' 연결 등록됨');});}}>
      <h3 className="full">연결 등록</h3><fieldset className="editor-fields full" disabled={busy}>
        <label>연결 이름<input aria-label="연결 이름" required maxLength={160} value={connection.title} onChange={event=>setConnection({...connection,title:event.target.value})}/></label>
        <label>연결 프로토콜<select aria-label="연결 프로토콜" value={connection.protocol} onChange={event=>{const protocol=event.target.value as ProviderProtocol;setSolGateway('vercel');setConnection({...connection,protocol,endpoint:roots[protocol],credentialEnv:credentials[protocol]});}}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
        {solConnection&&<label>Sol 게이트웨이<select aria-label="Sol 게이트웨이" value={solGateway} onChange={event=>{const id=event.target.value as typeof solGateway;setSolGateway(id);const gateway=SOL_GATEWAYS.find(item=>item.id===id);setConnection({...connection,endpoint:gateway?.endpoint??'http://127.0.0.1:8080/v1',credentialEnv:gateway?.credentialEnv??''});}}>{SOL_GATEWAYS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}<option value="local">로컬 Responses 연결</option></select></label>}
        <label className="full">{endpointLabel}<input aria-label={endpointLabel} type="url" required readOnly={official} placeholder={vertexConnection?'https://aiplatform.googleapis.com/v1/projects/PROJECT_ID/locations/global/publishers/google/models':connection.protocol==='fixture-sse-v1'?'http://127.0.0.1:포트':'https://provider.example/v1'} value={connection.endpoint} onChange={event=>setConnection({...connection,endpoint:event.target.value})}/></label>
        <label>서버 환경변수 이름<input aria-label="서버 환경변수 이름" autoComplete="off" required={official} pattern="NARRATIVE_PROVIDER_[A-Z0-9_]+" placeholder={vertexConnection?'비우면 서버 ADC 사용':'NARRATIVE_PROVIDER_NAME'} value={connection.credentialEnv} onChange={event=>setConnection({...connection,credentialEnv:event.target.value})}/></label>
        {vertexConnection&&<label>Vertex 요청 요금제<select aria-label="Vertex 요청 요금제" value={connection.requestTier} onChange={event=>setConnection({...connection,requestTier:event.target.value as 'standard'|'flex'})}><option value="flex">Flex · 지연 가능, 자동 Standard 전환 없음</option><option value="standard">Standard</option></select></label>}
        <label className="check"><input type="checkbox" checked={connection.enabled} onChange={event=>setConnection({...connection,enabled:event.target.checked})}/>이 연결 사용</label>
        <small className="full">{vertexConnection?'환경변수 이름을 비우면 서버의 GOOGLE_APPLICATION_CREDENTIALS 파일로 인증해요. 입력하면 해당 환경변수의 Bearer token을 사용해요. 서버의 NR_VERTEX_REQUEST_TIER 설정이 요금제 선택보다 우선해요.':connection.protocol==='openai-chat-v1'?'기본 주소 뒤에 /chat/completions를 붙여요. 인증이 없는 로컬 서버는 환경변수 이름을 비워 두세요. 호환 범위는 공급자마다 달라요.':'인증 키 값은 입력하지 마세요. 서버에서 해당 환경변수와 NR_PROVIDER_ORIGINS 허용 주소를 설정한 다음 사용할 수 있어요.'}</small>
        {connection.protocol==='vercel-chat-v1'&&<small className="full">Vercel AI Gateway key를 환경변수에 넣고 모델 ID는 공급자/모델 형식으로 지정해요.</small>}
        {solConnection&&<small className="full">Sol은 Responses 형식으로 연결해요. Vercel 모델 ID는 공급자/모델 형식이고, 다른 게이트웨이는 해당 공급자의 모델 ID를 사용해요. 로컬 연결은 127.0.0.1 또는 [::1]의 /v1 주소만 허용해요.</small>}
      </fieldset><button disabled={busy}>연결 등록</button>
    </form>
    {library.models.length>0&&<section className="registered-models"><h3>저장한 모델 프리셋</h3><ul>{library.models.map(item=><li key={ref(item)}><strong>{item.title}</strong><small>{item.modelId} · 최대 {item.maxOutputTokens.toLocaleString()} 토큰{item.thinkingLevel&&' · 생각 '+item.thinkingLevel}{item.timeoutMs!==undefined&&' · 제한 '+item.timeoutMs/1000+'초'}</small></li>)}</ul></section>}
    <form className="editor-grid" onSubmit={event=>{event.preventDefault();if(!chosen)return;void perform(async()=>{const created=await api<ModelPreset>('/model-presets',{title:model.title,connectionId:chosen.id,connectionRevision:chosen.revision,modelId:model.modelId,maxOutputTokens:model.maxOutputTokens,temperature:vertexModel||model.temperature===''?null:Number(model.temperature),...(vertexModel?{thinkingLevel:model.thinkingLevel}:{}),...(!fixture?{timeoutMs:Math.round(model.timeoutSeconds*1000)}:{}),...(solModel?{sol}:{}),...(!vertexModel&&!fixture?{...(model.structuredOutput!=='default'?{structuredOutput:model.structuredOutput==='on'}:{}),...(model.reasoningEffort?{reasoningEffort:model.reasoningEffort}:{}),...(anthropic&&model.thinkingMode?{thinkingMode:model.thinkingMode,...(model.thinkingMode==='enabled'?{thinkingBudgetTokens:model.thinkingBudgetTokens}:{})}:{} )}:{} )});setMessage(created.title+' 모델 프리셋 등록됨');});}}>
      <h3 className="full">모델 프리셋 등록</h3><fieldset className="editor-fields full" disabled={busy}>
        <label>모델 프리셋 이름<input aria-label="모델 프리셋 이름" required maxLength={160} value={model.title} onChange={event=>setModel({...model,title:event.target.value})}/></label>
        <label>모델 연결<select aria-label="모델 연결" required value={model.connectionRef} onChange={event=>{const next=library.connections.find(item=>ref(item)===event.target.value);const vertex=next?.protocol==='vertex-gemini-v1';setSol(defaultSolOptions());setModel({...model,connectionRef:event.target.value,modelId:vertex?VERTEX_GEMINI_MODEL_ID:'',temperature:'',reasoningEffort:'',thinkingMode:'',structuredOutput:'default',maxOutputTokens:vertex?Math.min(model.maxOutputTokens,VERTEX_GEMINI_MAX_OUTPUT_TOKENS):model.maxOutputTokens});}}><option value="">연결 선택</option>{library.connections.map(item=><option key={ref(item)} value={ref(item)}>{item.title} · v{item.revision}</option>)}</select></label>
        <label>모델 ID<input aria-label="모델 ID" list="available-models" required readOnly={vertexModel} value={model.modelId} onChange={event=>setModel({...model,modelId:event.target.value})}/><datalist id="available-models">{chosen?.catalog.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</datalist></label>
        <label>최대 출력 토큰<input aria-label="최대 출력 토큰" type="number" min={1} max={vertexModel?VERTEX_GEMINI_MAX_OUTPUT_TOKENS:200000} required value={model.maxOutputTokens} onChange={event=>setModel({...model,maxOutputTokens:Number(event.target.value)})}/></label>
        {vertexModel?<label>생각 수준<select aria-label="생각 수준" value={model.thinkingLevel} onChange={event=>setModel({...model,thinkingLevel:event.target.value as NonNullable<ModelPreset['thinkingLevel']>})}>{['LOW','MEDIUM','HIGH'].map(value=><option key={value}>{value}</option>)}</select></label>:<label>Temperature<input aria-label="Temperature" type="number" step={0.1} min={0} max={anthropic?1:2} placeholder="공급자 기본값" value={model.temperature} onChange={event=>setModel({...model,temperature:event.target.value})}/></label>}
        {!fixture&&<label>응답 제한 시간 (초)<input aria-label="응답 제한 시간 (초)" type="number" min={1} max={1800} required value={model.timeoutSeconds} onChange={event=>setModel({...model,timeoutSeconds:Number(event.target.value)})}/></label>}
        {vertexModel?<small className="full">Gemini 3.8 Flash는 Temperature를 사용하지 않아요. Flex는 응답이 늦을 수 있어 제한 시간을 최대 1800초까지 늘릴 수 있어요.</small>:<small className="full">모델의 옵션 지원 여부를 확인해 저장하세요. 미지원 옵션 때문에 실패해도 앱이 옵션을 바꿔 자동 재요청하지 않아요.</small>}
        {chosen&&!vertexModel&&!fixture&&<details className="full"><summary>선택 옵션 · 모델이 지원할 때 사용</summary><div className="editor-grid">
          <label>번역 구조화 출력<select aria-label="번역 구조화 출력" value={model.structuredOutput} onChange={event=>setModel({...model,structuredOutput:event.target.value})}><option value="default">연결 기본값</option><option value="on">JSON Schema 사용</option><option value="off">지침과 결과 검증만 사용</option></select></label>
          <label>Reasoning effort<select aria-label="Reasoning effort" value={model.reasoningEffort} onChange={event=>setModel({...model,reasoningEffort:event.target.value})}><option value="">공급자 기본값</option>{(anthropic?['low','medium','high','xhigh','max']:solModel?['none','minimal','low','medium','high','xhigh','max']:['none','minimal','low','medium','high','xhigh']).map(value=><option key={value}>{value}</option>)}</select></label>
          {anthropic&&<><label>Thinking<select aria-label="Thinking" value={model.thinkingMode} onChange={event=>setModel({...model,thinkingMode:event.target.value})}><option value="">공급자 기본값</option><option value="disabled">disabled</option><option value="adaptive">adaptive</option><option value="enabled">enabled · 토큰 예산 지정</option></select></label>{model.thinkingMode==='enabled'&&<label>Thinking 토큰 예산<input aria-label="Thinking 토큰 예산" type="number" min={1024} max={model.maxOutputTokens-1} value={model.thinkingBudgetTokens} onChange={event=>setModel({...model,thinkingBudgetTokens:Number(event.target.value),temperature:''})}/></label>}</>}
          <small className="full">OpenAI Responses·Anthropic은 번역에 JSON Schema를 기본 사용해요. Vercel·별도 호환 공급자는 기본 미사용이며 결과 검증은 항상 적용해요.</small>
        </div></details>}
        {solModel&&<fieldset className="editor-fields full"><legend>Sol 도구와 출력</legend>
          <label className="full">Sol 문맥 제공<select aria-label="Sol 문맥 제공" value={sol.contextMode} onChange={event=>setSol({...sol,contextMode:event.target.value as SolOptions['contextMode']})}><option value="model-selected">모델이 필요한 도구 선택</option><option value="preloaded">로컬 문맥 먼저 제공</option></select></label>
          <label>Sol 추가 도구 라운드<input aria-label="Sol 추가 도구 라운드" type="number" min={0} max={32} required value={sol.maximumToolRounds} onChange={event=>setSol({...sol,maximumToolRounds:Number(event.target.value)})}/></label>
          <label className="check"><input type="checkbox" checked={sol.terminalLateCorrections} onChange={event=>setSol({...sol,terminalLateCorrections:event.target.checked})}/>제출 원고의 정확한 문자열 교정 허용</label>
          <small className="full">일반 텍스트 응답과 원고 제출을 모두 받아요. 제출 도구의 별도 안내문은 원문에 합치지 않아요. 도구는 기존 읽기 권한 안에서만 동작하며, 라운드 수는 이야기의 전체 모델 호출 한도에도 제한돼요.</small>
          <details className="full"><summary>Sol 공급자 선택 옵션</summary><div className="editor-grid">
            <SolChoice label="Service tier" option="serviceTier" options={['auto','default','flex','priority']} value={sol} onChange={setSol}/>
            <SolChoice label="Verbosity" option="verbosity" options={['low','medium','high']} value={sol} onChange={setSol}/>
            <SolChoice label="Reasoning summary" option="reasoningSummary" options={['auto','concise','detailed']} value={sol} onChange={setSol}/>
            <label className="check"><input type="checkbox" checked={sol.includeEncryptedReasoning===true} onChange={event=>{const {includeEncryptedReasoning:_,...rest}=sol;setSol(event.target.checked?{...rest,includeEncryptedReasoning:true}:rest);}}/>Encrypted reasoning 연속 요청에 사용</label>
            <small className="full">선택하지 않은 옵션은 전송하지 않아요. 게이트웨이와 모델이 지원하는 옵션만 선택하세요. 추론 내용은 이야기 원문에 합치지 않아요.</small>
          </div></details>
        </fieldset>}
      </fieldset><button disabled={busy||!chosen}>모델 프리셋 등록</button>
    </form>{error&&<p className="error" role="alert">{error}</p>}<p role="status">{message}</p>
  </section>;
}

function SolChoice({label,option,options,value,onChange}:{label:string;option:'serviceTier'|'verbosity'|'reasoningSummary';options:string[];value:SolOptions;onChange:(value:SolOptions)=>void}) {
  return <label>{label}<select aria-label={label} value={value[option]??''} onChange={event=>{const next={...value};delete next[option];onChange(event.target.value?{...next,[option]:event.target.value}:next);}}><option value="">전송 안 함 · 공급자 기본값</option>{options.map(item=><option key={item} value={item}>{item}</option>)}</select></label>;
}
