import { useEffect, useId, useState } from 'react';
import type { RisuContent } from '../core/risu-content.js';
import { detectRisuImageHandoff } from '../core/risu-image-handoff.js';
import {
  nativeRisuBackground,
  nativeRisuExtension,
  nativeRisuLore,
  nativeRisuRegex,
  nativeRisuTriggers,
  normalizeRisuContentSource,
  validateRisuContentSource,
  type RisuContentSource,
} from '../core/risu-native.js';
import { useBufferedEditorState, useUnappliedEditorField } from './editor-workspace-context.js';
import { PackagePortraitEditor } from './PackagePortraitEditor.js';
import { PackageFeaturesEditor } from './PackageFeaturesEditor.js';
import { RisuImageHandoffFields } from './RisuImageHandoffFields.js';
import { NativeCollectionEditor } from './NativeCollectionEditor.js';
import { NativeRisuLoreEditor } from './NativeRisuLoreEditor.js';
import { NativeRisuAssetsEditor } from './NativeRisuAssetsEditor.js';
import { NativeRisuRegexEditor } from './NativeRisuRegexEditor.js';
import { SectionNavigation } from './SectionNavigation.js';
import './native-editor.css';

const object = (value: unknown): Record<string, unknown> =>
  value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
const string = (value: unknown) => (typeof value === 'string' ? value : '');
type SourcePart = 'greetings' | 'lore' | 'regex' | 'triggers' | 'card' | 'module';
type Section = 'basic' | 'greetings' | 'lore' | 'assets' | 'advanced' | 'creator';
type Advanced = 'instructions' | 'variables' | 'display' | 'scripts' | 'modules' | 'source';

/** Forms edit native fields; package summaries are regenerated by the save boundary. */
export function RisuNativeFields({
  value,
  onChange,
  onDraftChange,
  onPortraitBusy,
}: {
  value: RisuContent;
  onChange: (value: RisuContent) => void;
  onDraftChange: (dirty: boolean) => void;
  onPortraitBusy: (busy: boolean) => void;
}) {
  const native = value.nativeRisu;
  const standalone = !Object.keys(native.card).length && !!native.module;
  const id = useId();
  const [section, setSection] = useState<Section>('basic');
  const [advanced, setAdvanced] = useState<Advanced>('instructions');
  const [part, setPart] = useState<SourcePart>('lore');
  const [draft, setDraft] = useBufferedEditorState<{ part: SourcePart; text: string } | null>(
    'package.native.source',
    null
  );
  const [error, setError] = useState('');
  const [modulesDirty, setModulesDirty] = useState(false);
  const [regexDirty, setRegexDirty] = useState(false);
  const [portraitBusy, setPortraitBusy] = useState(false);
  const [assetsBusy, setAssetsBusy] = useState(false);
  useEffect(() => {
    onPortraitBusy(portraitBusy || assetsBusy);
  }, [portraitBusy, assetsBusy, onPortraitBusy]);
  useEffect(() => () => onPortraitBusy(false), [onPortraitBusy]);
  useUnappliedEditorField('package.native.source', !!draft);
  useEffect(() => {
    onDraftChange(!!draft || modulesDirty || regexDirty);
  }, [draft, modulesDirty, regexDirty, onDraftChange]);
  useEffect(() => () => onDraftChange(false), [onDraftChange]);
  const update = (input: RisuContentSource) => {
    const next = normalizeRisuContentSource(input);
    onChange({
      ...value,
      title: string(standalone ? next.module?.name : next.card.name),
      nativeRisu: next,
      imageHandoff: detectRisuImageHandoff(next, value.imageHandoff),
    });
  };
  const field = (key: string, next: string) =>
    update({
      ...native,
      ...(standalone
        ? { module: { ...native.module, [key]: next } }
        : { card: { ...native.card, [key]: next } }),
    });
  const extension = (key: string, next: string) =>
    update({
      ...native,
      card: {
        ...native.card,
        extensions: {
          ...object(native.card.extensions),
          risuai: { ...nativeRisuExtension(native), [key]: next },
        },
      },
    });
  const lore = nativeRisuLore(native);
  const regex =
    (native.module ? native.module.regex : nativeRisuExtension(native).customScripts) ?? [];
  const writeRegex = (entries: unknown[]) =>
    update({
      ...native,
      ...(native.module
        ? { module: { ...native.module, regex: entries } }
        : {
            card: {
              ...native.card,
              extensions: {
                ...object(native.card.extensions),
                risuai: { ...nativeRisuExtension(native), customScripts: entries },
              },
            },
          }),
    });
  const moduleLore = native.module?.lorebook != null || standalone;
  const writeLore = (entries: Record<string, unknown>[]) =>
    update({
      ...native,
      ...(moduleLore
        ? { module: { ...native.module, lorebook: entries } }
        : {
            card: {
              ...native.card,
              character_book: { ...object(native.card.character_book), entries },
            },
          }),
    });
  const greetings = [
    string(native.card.first_mes),
    ...(Array.isArray(native.card.alternate_greetings)
      ? native.card.alternate_greetings.map(string)
      : []),
  ];
  const writeGreetings = (entries: string[]) =>
    update({
      ...native,
      card: { ...native.card, first_mes: entries[0] ?? '', alternate_greetings: entries.slice(1) },
    });
  const selectedPart = draft?.part ?? part;
  const source = {
    greetings: native.card.alternate_greetings ?? [],
    lore,
    regex: native.module
      ? (native.module.regex ?? [])
      : (nativeRisuExtension(native).customScripts ?? []),
    triggers: native.module
      ? (native.module.trigger ?? [])
      : (nativeRisuExtension(native).triggerscript ?? []),
    card: native.card,
    module: native.module ?? {},
  }[selectedPart];
  function applyJson() {
    if (!draft) return;
    try {
      const parsed: unknown = JSON.parse(draft.text);
      const next = structuredClone(native);
      if (draft.part === 'card' || draft.part === 'module') {
        if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed))
          throw new Error('JSON 객체를 입력해 주세요.');
        next[draft.part] = parsed as Record<string, unknown>;
      } else {
        if (!Array.isArray(parsed)) throw new Error('JSON 배열을 입력해 주세요.');
        if (draft.part === 'greetings') {
          if (parsed.some((item) => typeof item !== 'string'))
            throw new Error('시작문은 문자열 배열로 입력해 주세요.');
          next.card.alternate_greetings = parsed;
        } else {
          if (parsed.some((item) => !item || typeof item !== 'object' || Array.isArray(item)))
            throw new Error('각 항목은 JSON 객체여야 해요.');
          if (draft.part === 'lore') {
            if (moduleLore) next.module = { ...next.module, lorebook: parsed };
            else
              next.card.character_book = { ...object(next.card.character_book), entries: parsed };
          } else if (next.module)
            next.module[draft.part === 'regex' ? 'regex' : 'trigger'] = parsed;
          else
            next.card.extensions = {
              ...object(next.card.extensions),
              risuai: {
                ...nativeRisuExtension(next),
                [draft.part === 'regex' ? 'customScripts' : 'triggerscript']: parsed,
              },
            };
        }
      }
      update(validateRisuContentSource(next));
      setDraft(null);
      setError('');
    } catch (caught) {
      setError((caught as Error).message);
    }
  }
  const sections: { id: Section; title: string }[] = [
    { id: 'basic', title: '기본 정보' },
    ...(!standalone ? [{ id: 'greetings' as const, title: '첫 메시지' }] : []),
    { id: 'lore', title: '로어북' },
    { id: 'assets', title: '에셋' },
    { id: 'advanced', title: '고급 설정' },
    ...(!standalone ? [{ id: 'creator' as const, title: '제작 정보' }] : []),
  ];
  const panel = (key: Section) => ({
    id: id + '-' + key + '-panel',
    role: 'tabpanel' as const,
    'aria-labelledby': id + '-' + key + '-tab',
    hidden: section !== key,
  });
  const rawEditor = (
    <div className="native-source-editor">
      <p className="muted">
        로어 {lore.length}개 · 정규식 {nativeRisuRegex(native).length}개 · 트리거{' '}
        {nativeRisuTriggers(native).length}개
      </p>
      <label>
        편집 대상
        <select
          aria-label="Risu 원문 편집 대상"
          value={selectedPart}
          disabled={!!draft}
          onChange={(e) => setPart(e.target.value as SourcePart)}
        >
          {!standalone && <option value="greetings">대체 시작문</option>}
          <option value="lore">로어</option>
          <option value="regex">정규식</option>
          <option value="triggers">트리거 / Lua</option>
          {!standalone && <option value="card">카드 전체 JSON</option>}
          {native.module && <option value="module">모듈 전체 JSON</option>}
        </select>
      </label>
      <label>
        원문 JSON
        <textarea
          className="native-main-text"
          aria-label="Risu 원문 JSON"
          rows={18}
          spellCheck={false}
          value={draft?.text ?? JSON.stringify(source, null, 2)}
          onChange={(e) => setDraft({ part: selectedPart, text: e.target.value })}
        />
      </label>
      <div className="form-actions">
        <button type="button" disabled={!draft} onClick={applyJson}>
          JSON 적용
        </button>
        <button
          type="button"
          className="ghost"
          disabled={!draft}
          onClick={() => {
            setDraft(null);
            setError('');
          }}
        >
          입력 되돌리기
        </button>
      </div>
    </div>
  );
  return (
    <div className="native-editor native-content-editor full">
      <SectionNavigation
        label="자료 편집 영역"
        items={sections}
        value={section}
        onSelect={setSection}
        compact={false}
        orientation="horizontal"
        idPrefix={id}
      />
      {draft && (
        <p className="native-editor-notice" role="status">
          미적용 원문이 있어요.{' '}
          <button
            type="button"
            className="ghost"
            onClick={() => {
              setSection('advanced');
              setAdvanced('source');
            }}
          >
            원문 확인
          </button>
        </p>
      )}
      {error && (
        <p className="error" role="alert">
          {error} · 입력은 유지했어요.
        </p>
      )}
      <fieldset disabled={!!draft} className="native-panel-fields">
        <div {...panel('basic')} className="native-section-body">
          <PackagePortraitEditor
            value={value}
            onChange={onChange}
            onDirtyChange={setPortraitBusy}
          />
          <label>
            이름
            <input
              aria-label="Risu 자료 이름"
              value={string(standalone ? native.module?.name : native.card.name)}
              maxLength={200}
              onChange={(e) => field('name', e.target.value)}
            />
          </label>
          <label>
            {standalone ? '모듈 설명' : '디스크립션'}
            <textarea
              className="native-main-text native-description"
              aria-label={standalone ? '모듈 설명' : '캐릭터 설정'}
              rows={12}
              value={string(standalone ? native.module?.description : native.card.description)}
              onChange={(e) => field('description', e.target.value)}
            />
          </label>
        </div>
        {!standalone && (
          <div {...panel('greetings')}>
            <NativeCollectionEditor
              label="첫 메시지"
              items={greetings.map((message, i) => ({
                title: i === 0 ? '기본 첫 메시지' : '대체 메시지 ' + i,
                subtitle: message.replace(/<[^>]*>/g, '').slice(0, 55),
              }))}
              onAdd={() => writeGreetings([...greetings, ''])}
              onMove={(i, delta) => {
                const next = [...greetings];
                [next[i], next[i + delta]] = [next[i + delta], next[i]];
                writeGreetings(next);
              }}
              onRemove={(i) =>
                writeGreetings(greetings.length === 1 ? [''] : greetings.filter((_, n) => n !== i))
              }
            >
              {(i) => (
                <label>
                  {i === 0 ? '기본 시작문' : '대체 시작문'}
                  <textarea
                    className="native-main-text"
                    aria-label={i === 0 ? '기본 시작문' : '대체 시작문'}
                    rows={18}
                    value={greetings[i]}
                    onChange={(e) =>
                      writeGreetings(
                        greetings.map((message, n) => (n === i ? e.target.value : message))
                      )
                    }
                  />
                </label>
              )}
            </NativeCollectionEditor>
          </div>
        )}
        <div {...panel('lore')}>
          <NativeRisuLoreEditor
            entries={lore}
            moduleLore={moduleLore}
            onChange={writeLore}
            selectionControl={
              <label>
                로어 선택 방식
                <select
                  value={value.loreActivation?.mode ?? 'model'}
                  onChange={(e) =>
                    onChange({
                      ...value,
                      loreActivation: {
                        ...value.loreActivation,
                        mode: e.target.value as 'model' | 'discoverable',
                      },
                    })
                  }
                >
                  <option value="model">JEV 관련성 판단</option>
                  <option value="discoverable">필요할 때 모델이 읽기</option>
                </select>
              </label>
            }
          />
        </div>
        <div {...panel('assets')} className="native-section-body">
          <NativeRisuAssetsEditor value={value} onChange={onChange} onBusyChange={setAssetsBusy} />
        </div>
        {!standalone && (
          <div {...panel('creator')} className="native-section-body">
            <label>
              제작자 코멘트
              <textarea
                aria-label="제작자 코멘트"
                rows={4}
                value={string(native.card.creator_notes)}
                onChange={(e) => field('creator_notes', e.target.value)}
              />
            </label>
            <div className="native-field-row">
              <label>
                제작자
                <input
                  value={string(native.card.creator)}
                  onChange={(e) => field('creator', e.target.value)}
                />
              </label>
              <label>
                자료 버전
                <input
                  value={string(native.card.character_version)}
                  onChange={(e) => field('character_version', e.target.value)}
                />
              </label>
            </div>
          </div>
        )}
      </fieldset>
      <div
        {...panel('advanced')}
        className={`native-section-body native-advanced-workspace${advanced === 'scripts' ? ' native-regex-panel' : ''}`}
      >
        <div className="segmented native-advanced-tabs" role="group" aria-label="고급 설정 영역">
          {(
            [
              ['instructions', '지침'],
              ['variables', '기본 변수·토글'],
              ['display', '표시'],
              ['scripts', '스크립트'],
              ['modules', '연결 모듈'],
              ['source', '원문'],
            ] as const
          ).map(([key, title]) => (
            <button
              type="button"
              key={key}
              aria-pressed={advanced === key}
              onClick={() => {
                setAdvanced(key);
                if (key === 'scripts' && !draft) setPart('triggers');
              }}
            >
              {title}
            </button>
          ))}
        </div>
        <fieldset className="native-panel-fields" disabled={!!draft}>
          <div hidden={advanced !== 'instructions'} className="native-form-stack">
            {!standalone ? (
              <>
                <label>
                  글로벌노트
                  <textarea
                    rows={8}
                    value={string(native.card.post_history_instructions)}
                    onChange={(e) => field('post_history_instructions', e.target.value)}
                  />
                </label>
                <label>
                  대화 예시
                  <textarea
                    aria-label="대화 예시"
                    rows={8}
                    value={string(native.card.mes_example)}
                    onChange={(e) => field('mes_example', e.target.value)}
                  />
                </label>
              </>
            ) : (
              <p className="muted">카드의 글로벌노트와 대화 예시는 봇 편집에서 설정해요.</p>
            )}
          </div>
          <div hidden={advanced !== 'variables'} className="native-form-stack">
            <label>
              기본 변수
              <textarea
                rows={8}
                value={string(
                  standalone
                    ? native.module?.defaultVariables
                    : nativeRisuExtension(native).defaultVariables
                )}
                onChange={(e) =>
                  standalone
                    ? field('defaultVariables', e.target.value)
                    : extension('defaultVariables', e.target.value)
                }
              />
            </label>
            <label>
              토글 정의
              <textarea
                rows={8}
                value={string(
                  standalone
                    ? native.module?.customModuleToggle
                    : nativeRisuExtension(native).toggles
                )}
                onChange={(e) =>
                  standalone
                    ? field('customModuleToggle', e.target.value)
                    : extension('toggles', e.target.value)
                }
              />
            </label>
          </div>
          <div hidden={advanced !== 'display'} className="native-form-stack">
            {!standalone && (
              <label>
                배경 HTML / CSS
                <textarea
                  rows={12}
                  spellCheck={false}
                  value={nativeRisuBackground(native)}
                  onChange={(e) => extension('backgroundHTML', e.target.value)}
                />
              </label>
            )}
            {value.imageHandoff && (
              <RisuImageHandoffFields
                policy={value.imageHandoff}
                selected={value.imageHandoff.ranges
                  .filter((range) => range.enabled)
                  .map((range) => range.id)}
                onChange={(ids) =>
                  onChange({
                    ...value,
                    imageHandoff: {
                      ...value.imageHandoff!,
                      ranges: value.imageHandoff!.ranges.map((range) => ({
                        ...range,
                        enabled: ids.includes(range.id),
                      })),
                    },
                  })
                }
              />
            )}
          </div>
          <div hidden={advanced !== 'modules'}>
            <PackageFeaturesEditor
              value={value}
              onChange={onChange}
              onDirtyChange={setModulesDirty}
            />
          </div>
        </fieldset>
        <div hidden={advanced !== 'scripts'}>
          <NativeRisuRegexEditor
            value={Array.isArray(regex) ? regex : []}
            draftPath="package.native.regex"
            onChange={writeRegex}
            onPendingChange={setRegexDirty}
            disabled={!!draft}
          />
          <button
            type="button"
            className="ghost"
            onClick={() => {
              setAdvanced('source');
              if (!draft) setPart('triggers');
            }}
          >
            트리거·Lua 원문 편집
          </button>
        </div>
        {advanced === 'source' && (
          <fieldset className="native-panel-fields" disabled={regexDirty}>
            {rawEditor}
          </fieldset>
        )}
      </div>
    </div>
  );
}
