import { useRef, useState } from 'react';
import { api, saveDownload } from './api.js';
import type { RisuImportResult } from '../core/risu-import.js';

export function RisuImport({onImported,onClose}:{onImported:()=>Promise<void>;onClose:()=>void}){
  const [result,setResult]=useState<RisuImportResult|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [accepted,setAccepted]=useState(false);const [saved,setSaved]=useState(false);const version=useRef(0);
  async function inspect(file:File){const current=++version.current;setBusy(true);setError('');setResult(null);setAccepted(false);setSaved(false);
    try{if(file.size>16*1024*1024)throw new Error('파일은 최대 16MiB까지 읽을 수 있어요.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const next=await api<RisuImportResult>('/imports/risu/inspect',{fileName:file.name,dataBase64:btoa(binary)});if(current===version.current)setResult(next);}catch(e){if(current===version.current)setError((e as Error).message);}finally{if(current===version.current)setBusy(false);}}
  const blocked=result?.issues.some(i=>i.severity==='blocking');const warnings=result?.issues.some(i=>i.severity==='warning');
  return <section className="settings-stack" aria-label="자료 가져오기"><p>Uimori JSON과 Risu 캐릭터·프리셋·모듈 자료를 분석해요. 변환할 수 없는 동작은 적용 전에 알려줘요.</p><label>가져올 파일<input aria-label="가져올 자료 파일" type="file" accept=".json,.charx,.risup,.risum" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void inspect(file);}}/></label>{busy&&<p role="status">자료를 확인하는 중이에요…</p>}{error&&<p className="error" role="alert">{error}</p>}{result&&<><div><h3>{result.original?.fileName??'가져온 자료'}</h3><p>{blocked?'수정이 필요한 동작이 있어요.':warnings?'차이를 확인한 뒤 가져올 수 있어요.':'가져올 준비가 됐어요.'}</p></div><ul>{result.issues.map((issue,index)=><li key={index}><strong>{issue.severity==='blocking'?'수정 필요':issue.severity==='warning'?'변경점':'안내'}</strong> · {issue.message}<small> {issue.path}</small></li>)}</ul><details><summary>변환 결과와 원문 구조 보기</summary><pre style={{maxHeight:360,overflow:'auto',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({draft:result.draft,extracted:result.extracted},null,2)}</pre></details><button type="button" className="secondary" onClick={()=>saveDownload('uimori-conversion-review.json',result)}>Agent 변환 자료 내려받기</button><small>원문 구조·변경점·작성 안내를 함께 보관해요. 모델 호출은 하지 않아요.</small>{warnings&&!blocked&&<label className="check"><input aria-label="변환 차이 확인" type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>표시된 차이를 확인했어요.</label>}<button type="button" disabled={busy||saved||blocked||!result.draft||(warnings&&!accepted)} onClick={async()=>{setBusy(true);setError('');try{await api(result.kind==='prompt'?'/prompt-presets':'/content',result.draft);setSaved(true);await onImported();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{saved?'자료를 등록했어요':'검토한 자료 등록'}</button>{blocked&&<p className="muted">Agent가 변환 자료를 바탕으로 Uimori JSON을 작성한 뒤 다시 가져올 수 있어요. 지원하지 않는 내용을 실행하지 않도록 등록은 잠겨 있어요.</p>}</>}<button type="button" className="secondary" disabled={busy} onClick={onClose}>닫기</button></section>;
}
